# STATIC IP ADDRESS
#/etc/netplan/50-cloud-init.yaml
network:
    ethernets:
        eth0:
            optional: true
            dhcp4: false
            addresses: [192.168.x.y1/24]
            gateway4: 192.168.x.1
            nameservers:
              addresses: [8.8.8.8,8.8.4.4,192.168.x.1]
    version: 2

    wifis:
        wlan0:
            optional: true
            dhcp4: false
            addresses: [192.168.x.y2/24]
            gateway4: 192.168.x.1
            nameservers:
              addresses: [8.8.8.8,8.8.4.4,192.168.x.1]
            access-points:
                "your ssid":
                    password: "your password"
